baseURL = "https://alicanzeybek.xyz/"
languageCode = "en-us"
title = "Ali Can Zeybek"
theme = "lekh"

[params]
Name = "Ali Can Zeybek"
About = "I am a software engineer currently working as a research engineer in AirTies. I am highly invested in self deployed applications and web freedom."
Email = "ali.c.zeybek@gmail.com"
Resume = "" # Add the filename with file extension.
PostLimit = 4 # Sets the number of posts to display on the front page
GoatCounterCode = ""

[[params.profiles]]
name = "GitHub"
url = "https://github.com/ali-z-can"

#[[params.profiles]]
#name = "Twitter"
#url = "https://twitter.com/ba11b0y"

#[[params.profiles]]
#name = "Goodreads"
#url = "https://www.goodreads.com/user/show/91520565-rahul-tiwari"

[[params.profiles]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/ali-can-zeybek-a93296110/"

